<?php

use Illuminate\Database\Seeder;

class EmployesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      DB::table('employes')->insert([

      [
          'matricule' => 'COF587174',
          'numero_sss' => '7000',
          'nom' => 'KITSOUKOU',
          'prenom' => 'EMANNY',
          'password' => Hash::make('123456789'),
          'date_naissance' => '2019-05-01',
          'email' => 'emanny.kitsoukou@cofinacorp.com',
          'role' => 'CHECKER',
          'mail_perso' => 'emanny_uker@hotmail.com',
          'tel_pro' => '22547639495',
          'tel_perso' => '22578860519',
          'contact_urgent' => '22509834111',
          'entite' => 'CTI',
          'sexe' => 'MASCULIN',
          'photo' => 'photo.jpg',
          'civilite' => 'MONSIEURS',
          'situation_matrimoniale' => 'MARIEE',
          'nbre_enfant' => '0',
          'nationnalite' => 'CONGOLAISE',
          'origine' => 'CONGO',
          'secteur' => 'SALES',
          'categorie' => 'CADRE',
          'departement' => 'FINANCE',
          'pays' => 'COTE D IVOIRE'

      ],
      [
          'matricule' => 'COF5848674',
          'numero_sss' => '7001',
          'nom' => 'MADINGOU',
          'prenom' => 'MAKY',
          'password' => Hash::make('123456789'),
          'date_naissance' => '2000-02-01',
          'email' => 'emanny.kitsoukou@cofinacorp.fr',
          'role' => 'MAKER',
          'mail_perso' => 'emanny_uker@hotmail.fr',
          'tel_pro' => '22547639495',
          'tel_perso' => '22578860519',
          'contact_urgent' => '225',
          'entite' => 'CTI',
          'sexe' => 'MASCULIN',
          'photo' => 'photo.jpg',
          'civilite' => 'Monsieur',
          'situation_matrimoniale' =>'CELIBATAIRE',
          'nbre_enfant' => '1',
          'nationnalite' => 'CONGOLAISE',
          'origine' => 'CONGO',
          'secteur' => 'SALES',
          'categorie' => 'CADRE',
          'departement' => 'INFORMATIQUE',
          'pays' => 'COTE D IVOIRE'
      ],
      [
          'matricule' => 'COF5848275',
          'numero_sss' => '7003',
          'nom' => 'MILANDOU',
          'prenom' => 'LOIC ROXAN',
          'password' => Hash::make('123456789'),
          'date_naissance' => '1993-07-19',
          'email' => 'roxanmlr@gmail.com',
          'role' => 'MAKER',
          'mail_perso' => 'emanny_uker@hotmail.fr',
          'tel_pro' => '22547639495',
          'tel_perso' => '22578860519',
          'contact_urgent' => '225',
          'entite' => 'COFINA CG',
          'sexe' => 'MASCULIN',
          'photo' => 'photo.jpg',
          'civilite' => 'Monsieur',
          'situation_matrimoniale' =>'CELIBATAIRE',
          'nbre_enfant' => '0',
          'nationnalite' => 'CONGOLAISE',
          'origine' => 'CONGO',
          'secteur' => 'SALES',
          'categorie' => 'CADRE',
          'departement' => 'RESSOURCE HUMAINE',
          'pays' => 'CONGO'

      ],
      [
          'matricule' => 'COF5848645',
          'numero_sss' => '7006',
          'nom' => 'YOBOUE',
          'prenom' => 'ANITA',
          'password' => Hash::make('123456789'),
          'date_naissance' => '2000-02-01',
          'email' => 'estelle-anita.yoboue@cofinacorp.fr',
          'role' => 'MAKER',
          'mail_perso' => 'emanny_uker@hotmail.fr',
          'tel_pro' => '22577170895',
          'tel_perso' => '22508705945',
          'contact_urgent' => '225',
          'entite' => 'CTI',
          'sexe' => 'FEMININ',
          'photo' => 'photo.jpg',
          'civilite' => 'MADAME',
          'situation_matrimoniale' =>'CELIBATAIRE',
          'nbre_enfant' => '2',
          'nationnalite' => 'IVOIRIENNE',
          'origine' => 'COTE D IVOIRE',
          'secteur' => 'SALES',
          'categorie' => 'CADRE',
          'departement' => 'INFORMATIQUE',
          'pays' => 'COTE D IVOIRE'
      ],
      [
          'matricule' => 'COF5848649',
          'numero_sss' => '70010',
          'nom' => 'KOUAKOU',
          'prenom' => 'CARINE',
          'password' => Hash::make('123456789'),
          'date_naissance' => '2000-02-01',
          'email' => 'carine.kouakou@cofinacorp.fr',
          'role' => 'CHECKER',
          'mail_perso' => 'emanny_uker@hotmail.fr',
          'tel_pro' => '22589403480',
          'tel_perso' => '22507765566',
          'contact_urgent' => '22507765566',
          'entite' => 'CTI',
          'sexe' => 'FEMININ',
          'photo' => 'photo.jpg',
          'civilite' => 'MADAME',
          'situation_matrimoniale' =>'MARIEE',
          'nbre_enfant' => '1',
          'nationnalite' => 'IVOIRIENNE',
          'origine' => 'COTE D IVOIRE',
          'secteur' => 'SALES',
          'categorie' => 'CADRE',
          'departement' => 'RESSOURCE HUMAINE',
          'pays' => 'COTE D IVOIRE'
      ],
      [
          'matricule' => 'COF5128649',
          'numero_sss' => '70890',
          'nom' => 'YAGUE',
          'prenom' => 'MARIAME',
          'password' => Hash::make('123456789'),
          'date_naissance' => '2000-02-01',
          'email' => 'mariame.yague@cofinacorp.com',
          'role' => 'CHECKER',
          'mail_perso' => 'mariame.yague@hotmail.com',
          'tel_pro' => '22589403480',
          'tel_perso' => '22507765566',
          'contact_urgent' => '22507765566',
          'entite' => 'CTI',
          'sexe' => 'FEMININ',
          'photo' => 'photo.jpg',
          'civilite' => 'MADAME',
          'situation_matrimoniale' =>'MARIEE',
          'nbre_enfant' => '1',
          'nationnalite' => 'SENEGALAISE',
          'origine' => 'SENEGAL',
          'secteur' => 'SALES',
          'categorie' => 'CADRE',
          'departement' => 'RESSOURCE HUMAINE',
          'pays' => 'SENEGAL'
      ],
      [
          'matricule' => 'CTI5848001',
          'numero_sss' => '5021',
          'nom' => 'KOUASSI',
          'prenom' => 'LEONARD',
          'password' => Hash::make('123456789'),
          'date_naissance' => '2000-02-01',
          'email' => 'leonard.kouassi@cofinacorp.com',
          'role' => 'MAKER',
          'mail_perso' => 'leo@hotmail.fr',
          'tel_pro' => '0123456789',
          'tel_perso' => '9876543210',
          'contact_urgent' => '225',
          'entite' => 'CTI',
          'sexe' => 'MASCULIN',
          'photo' => 'photo.jpg',
          'civilite' => 'Monsieur',
          'situation_matrimoniale' =>'CELIBATAIRE',
          'nbre_enfant' => '1',
          'nationnalite' => 'IVOIRIENNE',
          'origine' => 'COTE D IVOIRE',
          'secteur' => 'SALES',
          'categorie' => 'CADRE',
          'departement' => 'INFORMATIQUE',
          'pays' => 'COTE D IVOIRE'

      ],
      [
          'matricule' => 'COF5005674',
          'numero_sss' => '1401',
          'nom' => 'DOGNON',
          'prenom' => 'MURIELLE',
          'password' => Hash::make('123456789'),
          'date_naissance' => '2000-02-01',
          'email' => 'murielle.dognon@cofinacorp.com',
          'role' => 'MAKER',
          'mail_perso' => 'murielle@yahoo.fr',
          'tel_pro' => '22547639495',
          'tel_perso' => '22578860519',
          'contact_urgent' => '225',
          'entite' => 'CTI',
          'sexe' => 'FEMININ',
          'photo' => 'photo.jpg',
          'civilite' => 'Madame',
          'situation_matrimoniale' =>'CELIBATAIRE',
          'nbre_enfant' => '1',
          'nationnalite' => 'BENINOISE',
          'origine' => 'BENIN',
          'secteur' => 'SALES',
          'categorie' => 'CADRE',
          'departement' => 'RESSOURCE HUMAINE',
          'pays' => 'SENEGAL'
      ],
      [
          'matricule' => 'CTI885674',
          'numero_sss' => '1001',
          'nom' => 'BALLOU',
          'prenom' => 'PEGGY',
          'password' => Hash::make('123456789'),
          'date_naissance' => '2000-02-01',
          'email' => 'peggy.ballou@cofinacorp.com',
          'role' => 'CHECKER',
          'mail_perso' => 'peggy@yahoo.fr',
          'tel_pro' => '22547639495',
          'tel_perso' => '22578860519',
          'contact_urgent' => '225',
          'entite' => 'CTI',
          'sexe' => 'FEMININ',
          'photo' => 'photo.jpg',
          'civilite' => 'Madame',
          'situation_matrimoniale' =>'MARIEE',
          'nbre_enfant' => '1',
          'nationnalite' => 'IVOIRIENNE',
          'origine' => 'COTE D IVOIRE',
          'secteur' => 'SALES',
          'categorie' => 'CADRE',
          'departement' => 'RESSOURCES HUMAINES',
          'pays' => 'COTE D IVOIRE'

      ],
      [
          'matricule' => 'CTIABJ5674',
          'numero_sss' => '1101',
          'nom' => '  SANE',
          'prenom' => 'YALIS',
          'password' => Hash::make('123456789'),
          'date_naissance' => '2000-02-01',
          'email' => 'yalis.sane@cofinacorp.com',
          'role' => 'MAKER',
          'mail_perso' => 'ysane@yahoo.fr',
          'tel_pro' => '22547639495',
          'tel_perso' => '22578860519',
          'contact_urgent' => '225',
          'entite' => 'CTI',
          'sexe' => 'FEMININ',
          'photo' => 'photo.jpg',
          'civilite' => 'Madame',
          'situation_matrimoniale' =>'MARIEE',
          'nbre_enfant' => '1',
          'nationnalite' => 'IVOIRIENNE',
          'origine' => 'COTE D IVOIRE',
          'secteur' => 'SALES',
          'categorie' => 'CADRE',
          'departement' => 'DMCC',
          'pays' => 'COTE D IVOIRE'
      ],
      [
          'matricule' => 'CTI822674',
          'numero_sss' => '1201',
          'nom' => 'MOLOU',
          'prenom' => 'EDWIGE',
          'password' => Hash::make('123456789'),
          'date_naissance' => '2000-02-01',
          'email' => 'edwige.molou@cofinacorp.com',
          'role' => 'CHECKER',
          'mail_perso' => 'edwigem@yahoo.fr',
          'tel_pro' => '22547639495',
          'tel_perso' => '22578860519',
          'contact_urgent' => '225',
          'entite' => 'CTI',
          'sexe' => 'FEMININ',
          'photo' => 'photo.jpg',
          'civilite' => 'Madame',
          'situation_matrimoniale' =>'CELIBATAIRE',
          'nbre_enfant' => '1',
          'nationnalite' => 'IVOIRIENNE',
          'origine' => 'COTE D IVOIRE',
          'secteur' => 'SALES',
          'categorie' => 'CADRE',
          'departement' => 'DMCC',
          'pays' => 'COTE D IVOIRE'
      ],
      [
          'matricule' => 'CTI885005',
          'numero_sss' => '1021',
          'nom' => 'SILUE',
          'prenom' => 'IBRAHAIMA',
          'password' => Hash::make('123456789'),
          'date_naissance' => '2000-02-01',
          'email' => 'ibrahima.silue@cofinacorp.com',
          'role' => 'CHECKER',
          'mail_perso' => 'isilue@yahoo.fr',
          'tel_pro' => '22547639495',
          'tel_perso' => '22578860519',
          'contact_urgent' => '225',
          'entite' => 'CTI',
          'sexe' => 'MASCULIN',
          'photo' => 'photo.jpg',
          'civilite' => 'Monsieur',
          'situation_matrimoniale' =>'CELIBATAIRE',
          'nbre_enfant' => '0',
          'nationnalite' => 'IVOIRIENNE',
          'origine' => 'COTE D IVOIRE',
          'secteur' => 'SALES',
          'categorie' => 'CADRE',
          'departement' => 'CONTROLE INTERNE',
          'pays' => 'COTE D IVOIRE',
      ],
      [
          'matricule' => 'CFN877001',
          'numero_sss' => '1023',
          'nom' => 'YAO',
          'prenom' => 'VICTOIRE',
          'password' => Hash::make('123456789'),
          'date_naissance' => '2000-02-01',
          'email' => 'victoire.yao@cofinacorp.com',
          'role' => 'CHECKER',
          'mail_perso' => 'vicky@yahoo.fr',
          'tel_pro' => '0123456789',
          'tel_perso' => '9876543210',
          'contact_urgent' => '225',
          'entite' => 'CTI',
          'sexe' => 'FEMININ',
          'photo' => 'photo.jpg',
          'civilite' => 'Madame',
          'situation_matrimoniale' =>'CELIBATAIRE',
          'nbre_enfant' => '0',
          'nationnalite' => 'IVOIRIENNE',
          'origine' => 'COTE D IVOIRE',
          'secteur' => 'SALES',
          'categorie' => 'CADRE',
          'departement' => 'FINANCE',
          'pays' => 'COTE D IVOIRE'
      ],
      [
          'matricule' => 'CFN877001',
          'numero_sss' => '1024',
          'nom' => 'MENSHAH',
          'prenom' => 'ANDRE',
          'password' => Hash::make('123456789'),
          'date_naissance' => '2000-02-01',
          'email' => 'andre.menshah@cofinacorp.com',
          'role' => 'CHECKER',
          'mail_perso' => 'andremansha@yahoo.fr',
          'tel_pro' => '0123456789',
          'tel_perso' => '9876543210',
          'contact_urgent' => '225',
          'entite' => 'CTI',
          'sexe' => 'MASCULIN',
          'photo' => 'photo.jpg',
          'civilite' => 'Monsieur',
          'situation_matrimoniale' =>'MARIEE',
          'nbre_enfant' => '2',
          'nationnalite' => 'TOGOLAISE',
          'origine' => 'TOGO',
          'secteur' => 'SALES',
          'categorie' => 'CADRE',
          'departement' => 'FINANCE',
          'pays' => 'COTE D IVOIRE'
      ],
      [
          'matricule' => 'CTI822114',
          'numero_sss' => '1201',
          'nom' => 'MORO',
          'prenom' => 'KEVIN',
          'password' => Hash::make('123456789'),
          'date_naissance' => '2000-02-01',
          'email' => 'kevin.moro@cofinacorp.com',
          'role' => 'CHECKER',
          'mail_perso' => 'kevinmoro@yahoo.fr',
          'tel_pro' => '225123456789',
          'tel_perso' => '22578860519',
          'contact_urgent' => '225',
          'entite' => 'CTI',
          'sexe' => 'MASCULIN',
          'photo' => 'photo.jpg',
          'civilite' => 'Monsieur',
          'situation_matrimoniale' =>'CELIBATAIRE',
          'nbre_enfant' => '1',
          'nationnalite' => 'IVOIRIENNE',
          'origine' => 'COTE D IVOIRE',
          'secteur' => 'SALES',
          'categorie' => 'CADRE',
          'departement' => 'DMCC',
          'pays' => 'COTE D IVOIRE'
      ],
      [
          'matricule' => 'COF5841250',
          'numero_sss' => '7112',
          'nom' => 'LEMBOKOLO',
          'prenom' => 'DIMITRI',
          'password' => Hash::make('123456789'),
          'date_naissance' => '2000-02-01',
          'email' => 'dimitri.lembokolo@cofinacorp.fr',
          'role' => 'MAKER',
          'mail_perso' => 'dl@hotmail.fr',
          'tel_pro' => '22547639495',
          'tel_perso' => '22578860519',
          'contact_urgent' => '225',
          'entite' => 'CSG',
          'sexe' => 'MASCULIN',
          'photo' => 'photo.jpg',
          'civilite' => 'Monsieur',
          'situation_matrimoniale' =>'MARIE',
          'nbre_enfant' => '1',
          'nationnalite' => 'CONGOLAISE',
          'origine' => 'CONGO',
          'secteur' => 'SALES',
          'categorie' => 'CADRE',
          'departement' => 'INFORMATIQUE',
          'pays' => 'GABON'
      ],
  ]);
    }
}
